// lib/locales/en/projects.ts
export type Project = {
  slug: string;
  title: string;
  short: string;
  description: string;
  imageSrc?: string;
  imageAlt?: string;
  tech: string[];
  demoUrl?: string;
  repoUrl?: string;
  date?: string;
};

export const projects: Project[] = [
  {
    slug: 'edd-shopify',
    title: 'Estimated Delivery Date',
    short: 'Shopify app to display accurate and customizable estimated delivery dates',
    description:
      'Estimated Delivery Date is an embedded Shopify app designed to dynamically display estimated delivery dates on product pages. ' +
      'It helps merchants improve transparency, build customer trust, and increase conversion rates by providing reliable delivery timeframes. ' +
      'The app includes advanced delivery calculation logic that takes into account business days, order cutoff times, preparation delays, and shipping ranges. ' +
      'It also features a template system with dynamic variables, a high level of widget customization (colors, style, compact mode, icon, etc.), and feature management through a Free / Pro plan system. ' +
      'Built with Shopify CLI, React, and TypeScript, it leverages Polaris and App Bridge for seamless integration within the Shopify admin, along with a Theme App Extension for lightweight storefront rendering. ' +
      'The project focuses on clear UX, simple configuration for merchants, highly reliable calculations, and a maintainable architecture suited for a solo developer.',
    imageSrc: '',
    imageAlt: 'Estimated delivery date widget on a Shopify product page',
    tech: ['Shopify CLI', 'React', 'TypeScript', 'Polaris', 'Shopify App Bridge'],
    date: '2026-03',
  },
  {
    slug: 'portfolio',
    title: 'Personal Portfolio',
    short: 'Dynamic CV and showcase of my projects',
    description:
      'This website is my personal portfolio. It showcases my skills, experiences and projects. ' +
      'Built with Next.js and React, it uses MUI for the UI and follows a modern architecture. ' +
      'It includes a contact page with my details and a downloadable PDF of my CV.',
    imageSrc: '',
    imageAlt: 'Screenshot of personal portfolio',
    tech: ['Next.js', 'React', 'TypeScript', 'MUI'],
    demoUrl: 'https://leo-jego.vercel.app',
    repoUrl: 'https://github.com/Kelkunx/Portfolio',
    date: '2025-09',
  },
  {
    slug: 'dashboard-news-ai',
    title: 'My News App',
    short: 'AI-powered news feed with custom filters',
    description:
      'Web application displaying a news feed filterable by categories and keywords. ' +
      'Each article includes a short summary automatically generated by an AI model (HuggingFace). ' +
      'The project pairs a React frontend with Tailwind CSS and a NestJS backend for data aggregation.',
    imageSrc: '/images/capture-news.png',
    imageAlt: 'Screenshot of the News AI dashboard',
    tech: ['React', 'NestJS', 'Tailwind', 'HuggingFace'],
    demoUrl: 'https://dashboard-news-ai.vercel.app',
    repoUrl: 'https://github.com/Kelkunx/dashboard-news-ai',
    date: '2025-08',
  },
  {
    slug: 'bts-baie-securisee',
    title: 'BTS Project — Secure Server Rack',
    short: 'Design and deployment of a secure server rack for a fictitious company',
    description:
      'School project carried out during BTS: design and deployment of a secure server rack. ' +
      'It included an Active Directory server, wired and wireless networks, a NAS, a camera system with motion detection, ' +
      'and temperature/humidity monitoring. ' +
      'I personally installed a RADIUS server connected to a Cisco access point and configured motion, temperature and humidity sensors with Arduino.',
    imageSrc: '',
    imageAlt: 'Illustration of a secure server rack',
    tech: ['Active Directory', 'Cisco', 'RADIUS', 'Arduino'],
    date: '2024-06',
  },
];
