// lib/locales/en/projects.ts
export type Project = {
  slug: string;
  title: string;
  short: string;
  description: string;
  imageSrc?: string;
  imageAlt?: string;
  tech: string[];
  demoUrl?: string;
  repoUrl?: string;
  date?: string;
};

export const projects: Project[] = [
  {
    slug: 'portfolio',
    title: 'Personal Portfolio',
    short: 'Dynamic CV and showcase of my projects',
    description:
      "This website is my personal portfolio. It showcases my skills, experiences and projects. " +
      "Built with Next.js and React, it uses MUI for the UI and follows a modern architecture. " +
      "It includes a contact page with my details and a downloadable PDF of my CV.",
    imageSrc: '',
    imageAlt: 'Screenshot of personal portfolio',
    tech: ['Next.js', 'React', 'TypeScript', 'MUI'],
    demoUrl: 'https://leo-jego.vercel.app',
    repoUrl: 'https://github.com/Kelkunx/Portfolio',
    date: '2025-09',
  },
  {
    slug: 'dashboard-news-ai',
    title: 'My News App',
    short: 'AI-powered news feed with custom filters',
    description:
      "Web application displaying a news feed filterable by categories and keywords. " +
      "Each article includes a short summary automatically generated by an AI model (HuggingFace). " +
      "The project pairs a React frontend with Tailwind CSS and a NestJS backend for data aggregation.",
    imageSrc: '/images/capture-news.png',
    imageAlt: 'Screenshot of the News AI dashboard',
    tech: ['React', 'NestJS', 'Tailwind', 'HuggingFace'],
    demoUrl: 'https://dashboard-news-ai.vercel.app',
    repoUrl: 'https://github.com/Kelkunx/dashboard-news-ai',
    date: '2025-08',
  },
  {
    slug: 'bts-baie-securisee',
    title: 'BTS Project — Secure Server Rack',
    short: 'Design and deployment of a secure server rack for a fictitious company',
    description:
      "School project carried out during BTS: design and deployment of a secure server rack. " +
      "It included an Active Directory server, wired and wireless networks, a NAS, a camera system with motion detection, " +
      "and temperature/humidity monitoring. " +
      "I personally installed a RADIUS server connected to a Cisco access point and configured motion, temperature and humidity sensors with Arduino.",
    imageSrc: '',
    imageAlt: 'Illustration of a secure server rack',
    tech: ['Active Directory', 'Cisco', 'RADIUS', 'Arduino'],
    date: '2024-06',
  },
];
